site_name: "Python Documentation by Use-Case: Making it Simple"
theme:
  name: material
nav:
  - Home: index.md
  - Data Cleaning: data-cleaning.md
  - Language Reference: language-reference.md
  - Testing MkDocs and Markdown: testing-mkdocs-and-markdown.md