site_name: "Python Documentation by Use-Case: Making it Simple"
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Data Cleaning: data-cleaning.md
  - Language Reference: language-reference.md
  - Testing MkDocs and Markdown: testing-mkdocs-and-markdown.md
  - Reference Manual: reference-manual.md
  - Introduction: introduction.md
  - Specification: specification.md
  - Syntax: syntax.md
  - Lexical Analysis: lexical-analysis.md
  - Testing Mermaid: testing_mermaid.md
  - Testing backticks: testing_backticks.md